sudo: required
language: generic
services: 
  - docker 

before_install:
  - sudo docker build -t manishamagi7/udemycourse-docker-react -f Dockerfile.dev .
  
script:
  - sudo docker run -e CI=true manishamagi7/udemycourse-docker-react npm run test